### PR TITLE
Xcode 9 beta 3 Support

### PR DESCRIPTION
**Pull request by stephencelis**
In Swift 3.2, `Dispatch.DispatchTimeInterval` has a new case, `.never`, that needs to be switched on.

Fixes https://github.com/ReactiveCocoa/ReactiveSwift/issues/483.

#### Checklist
- [ ] Updated CHANGELOG.md.

### CODE REVIEW

**Comment by mdiep** [comment]
Awesome! Thanks for tackling this. ✨

Would you mind targeting this against the `1.x-maintenance` branch instead? I think we should release this as a hot fix for 1.x so that people don't need to update to 2.x to use Xcode 9.

**Comment by stephencelis** [comment]
Sure thing! One sec, gotta clone/cherry-pick.

**Comment by stephencelis** [comment]
Done! No **CHANGELOG.md** on that branch. I imagine that'll get tackled when merging back into `master`?

**Comment by jakeadams** [comment]
I think some additional specs are in order. See `FoundationExtensionsSpec`. Additionally, I think the tests under this expectation are testing the wrong thing and can be fixed:
https://github.com/ReactiveCocoa/ReactiveSwift/blob/master/Tests/ReactiveSwiftTests/FoundationExtensionsSpec.swift#L108

**Comment by stephencelis** [comment]
Is it ReactiveSwift policy to test internal properties? Happy to tack on another commit here but wanted to unblock folks who are maintaining a Swift 3.2 branch of their apps.

**Comment by jakeadams** [comment]
Those properties already have test coverage (though one actually does not, in reality). I think adding test cases for the code change is the better way to ensure that folks are unblocked.

**Comment by stephencelis** [comment]
@jakeadams The fact that you can't really negate `.never` is gonna make for a very strange test 😅

**Comment by stephencelis** [comment]
Ah-ha! Fixing that test found a bug! `fatalError` on this line:

https://github.com/ReactiveCocoa/ReactiveSwift/blob/master/Sources/FoundationExtensions.swift#L96

Added assertions, fixed those tests, fixed the bug. Everything look good?

**Comment by mdiep** [comment]
This is fantastic! Thanks.

Once CI is green, I'll merge, release a hot fix, and merge the change into `master` as well.

**Comment by jakeadams** [comment]
Thanks @stephencelis! I'm looking forward to this getting released.

**Comment by mdiep** [comment]
@andersio If you want to do a 1.x release and then merge it into `master`, go ahead. Otherwise I'll do it later tonight or in the morning when I have time.

**Comment by alper** [comment]
Ok. So this is in 1.1.5? My ReactiveCocoa 5.0.4 does not seem to depend on it so I added the pod separately and that works.

**Pull request merged**
