### PR TITLE
Fix debounce when started twice

### PR DESCRIPTION
**Pull request by gpambrozio**
Fixes issue #771. Thanks @andersio for the quick solution on this.

I also added tests that show the solution works. The tests were added at a commit before the change that fixed it so it's easy to verify that tests fail before the change but not after.

#### Checklist
- [x] Updated CHANGELOG.md.

### CODE REVIEW

**Comment by gpambrozio** [comment]
@andersio not sure why this test failed ci:
```
/Users/travis/build/ReactiveCocoa/ReactiveSwift/Tests/ReactiveSwiftTests/SignalProducerSpec.swift:1060: error: -[ReactiveSwiftTests.SignalProducerSpec zip, can deal with hundreds of producers] : failed - Waited more than 1.0 second
```

It seems go only fail sometimes when I run the tests locally, might be indicative of a performance issue or just poor cpu management at the time it ran.

Adding a `(timeout: 2)` to that test makes it succeed all the time for me, even when my machine is building another project at the same time but I don't want to push this "fix" without getting some thoughts on it first.

**Comment by andersio** [comment]
@gpambrozio It is general flakiness of asynchronous test IMO. It can be rewritten it in terms of `TestScheduler` at a later point.

**Comment by gpambrozio** [comment]
@andersio do you want me to add the `timeout` change to this PR?

**Comment by andersio** [comment]
@gpambrozio It wouldn't be necessary. 👍

**Pull request merged**
