### PR TITLE
Joining empty list of producers fix

### PR DESCRIPTION
**Pull request by rocketnik**
#### Checklist
✅ Updated CHANGELOG.md.

### CODE REVIEW

**Comment by andersio** [comment]
Both `combineLatest` and `zip` have been designed to consistently emit _only_ array of N elements, given a sequence of N producers, and are documented to return an empty producer if the sequence of producer is empty. So we cannot change the default behavior silently here, though I do see the ergonomic value here.

The best option, IMO, would be to make it an opt-in option, e.g. `noUpstreamSentinel: [S.Iterator.Element.Value]?` on `combineLatest` and `zip` that accepts a `Sequence`.

**Comment by rocketnik** [comment]
@andersio please check again.

I agree with not breaking old code and went with your idea.

For private functions, I made this parameter mandatory, while for public ones I gave it a default value of `nil` resulting in the exact same behavior as before.

Please notice the implementation of `func all` and `func and`, for which I have provided a sentinel (`[]`). It looked like the old implementation was expecting an empty list to be returned already, but actually, this could not have happened.

**Comment by rocketnik** [comment]
Resolved conflict. @andersio Please recheck, when you find the time.

**Comment by rocketnik** [comment]
Any update on this?

**Comment by rocketnik** [comment]
Any update on this?

**Pull request merged**
