### PR TITLE
[WIP] Merging from Rex.

### PR DESCRIPTION
**Pull request by andersio**
Still WIP.

### CODE REVIEW

**Comment by NachoSoto** [comment]
Hmm is this to bring `Rex` to `ReactiveSwift`? If so I'm a big :-1::-1::-1:

**Comment by andersio** [comment]
@mdiep seems leaning to preserve the history when I last asked, so I worked it out. The option to squash and merge is still here, anyway.

**Comment by NachoSoto** [comment]
It's not about the history, it's about bringing (part of?) `Rex`. What's the reasoning behind this?
What logic did you follow to decide what to include in this PR?

**Comment by andersio** [comment]
The separation is solely based on the dependencies or its nature (Cocoa or ObjC, etc), as I thought it was about merging in everything from Rex. Perhaps I should focus on bringing the bindings and Cocoa extensions instead, and leave the operators alone.

**Comment by mdiep** [comment]
I think the confusion is that Rex is meant to go into ReactiveCocoa, not ReactiveSwift.

**Comment by andersio** [comment]
There are quite a few bits in Rex that is not Cocoa specific, and is extending the core ReactiveSwift.

**Comment by ikesyo** [comment]
Those are __extensions__ and should not be the core ReactiveSwift API I think.

**Comment by neilpa** [comment]
Yea, the idea I was to extract the Cocoa-specific bindings and use that as a new baseline for a Swift-centric Reactive Cocoa. The rest of Rex was mostly experimental operators that were ports from other Objective-C projects of mine. Those are probably too specific to be included in ReactiveSwift.

**Pull request closed without merging**
