### PR TITLE
Swift 4.1 migration

### PR DESCRIPTION
**Pull request by NachoSoto**
_Last updated and tested on: `Xcode 9.3 GM`._

#### Checklist
- [x] Updated CHANGELOG.md.
- [x] Remove `BindingSource` workarounds
- [x] Make `Signal.Event` and `ActionError` ` Equatable`
- [x] `.flatMap` -> `.compactMap`
- [x] Remove no longer necessary `Result.materialize` extension
- [x] Wait for `Xcode 9.3`
- [x] Update `Travis`
- [x] ~~Tag [final `Result` release](https://github.com/antitypical/Result/pull/259)~~ Can be done separately.
- [x] ~~Wait for fix to [`.logEvents` regression](https://bugs.swift.org/browse/SR-6796)~~ -> _[Workaround is implemented](https://github.com/ReactiveCocoa/ReactiveSwift/pull/590/commits/5bcb5e7e11062255abd9567da9b8c543bbeed70e), doesn't seem like they'll fix the regression._
- [x] Maintain `Swift 4.0.x` compatibility using `#if swift(>=4.1)`
- [x] Verify `UnsafeMutablePointer` deprecation changes (I'm not totally sure about them)

### CODE REVIEW

**Comment by andersio** [comment]
The where clauses for `Error` in `Property.swift` can be removed presumably.

**Comment by NachoSoto** [comment]
@andersio yup, done!

**Comment by NachoSoto** [comment]
Tested this on beta 2, tests still passing but the [regression](https://bugs.swift.org/browse/SR-6796) is still not fixed.

**Comment by NachoSoto** [comment]
I can't believe we need this workaround: https://github.com/ReactiveCocoa/ReactiveSwift/pull/590/commits/b2de826b67b0f8de8fcfc8eae29085cb7ec00056 🤦‍♂️

**Comment by sharplet** [comment]
See also http://forums.swift.org/t/more-consistent-function-types/9765/1

**Comment by mishagray** [comment]
I'm seeing an issue with swift 4.1 compability and this PR:
https://github.com/ReactiveCocoa/ReactiveSwift/pull/601

Basically.. all of my my 'signal.map {  Int($0) }` is now resolving to a SignalProducer with a value that is a closure, and when I click on 'map' it resolves to the new map method from https://github.com/ReactiveCocoa/ReactiveSwift/pull/601

Not sure how it behaves in swift 4.0, but swift 4.1 has issues.  Not sure if this is just a bug in 9.3 beta 2.

**Comment by NachoSoto** [comment]
Interesting. Any chance you can provide a small test case for that? I can take a look, and maybe add it to the test suite.

**Comment by mishagray** [comment]
```
	let fetchImage = SignalProducer<UIImage, NoError>(value: UIImage())
	let optionalFetch = fetchImage.map { $0 as UIImage? }

	assert(optionalFetch is SignalProducer<UIImage?, NoError>)
```

So in swift 4.0 ... optionalFetch will be the expected type ```SignalProducer<UIImage?, NoError>```.    In swift 4.1 ... we get ```SignalProducer<(UIImage?) -> UIImage?, NoError>```

**Comment by NachoSoto** [comment]
What happens if you do:
```
let optionalFetch2: SignalProducer<UIImage?, NoError>  = fetchImage.map { $0 as UIImage? }
```

**Comment by mishagray** [comment]
Ah... so this isn't NOT related to swift 4.1.   I wrote that code above and got the same warning error on assertion line 'Cast from 'SignalProducer<(UIImage?) -> UIImage?, NoError>' to unrelated type 'SignalProducer<UIImage?, NoError>' always fails' 

Every line compiles in swift 4.0/swift 4.1.   I could just open this as in issue against https://github.com/ReactiveCocoa/ReactiveSwift/pull/601.   Since it's not actually realted to 4.1.

I just first saw it in my swift 4.1 branch, but I think it's unrelated to swift 4.1

**Comment by NachoSoto** [comment]
Ooooh yup, totally, it's related to #601, bad overload resolution :( Can you open an issue for that?
Thanks!

**Comment by mbuchetics** [comment]
What's the current status now that Xcode 9.3 and Swift 4.1 are officially released?

**Comment by NachoSoto** [comment]
I'm away for a month and won't be able to continue working on this, somebody else please pick it up from here? 😊

**Comment by mdiep** [comment]
The current ReactiveSwift release works with Xcode 9.3 / Swift 4.1. It just has some warnings.

**Comment by gunterhager** [comment]
Interesting. You're right, i've just tested it. It seems to work with Xcode 9.4/Swift 4.1.1 beta, too. Used to fail with older Xcode 9.3 betas.

**Comment by andersio** [comment]
@ikesyo any plan to release Result with Swift 4.1 soon?

**Comment by ikesyo** [comment]
@andersio Sorry for the delay, Result 4.0 has been released 🚢 

https://github.com/antitypical/Result/releases/tag/4.0.0

**Comment by mdiep** [comment]
Do we want to maintain Xcode 9.2 / Swift 4.0.1 compatibility? As-is, this breaks compatibility (from changes I made) but retains some code for Swift <4.1. I'm not sure whether we should rip out the shims or add more in.

**Pull request merged**
