### PR TITLE
Use AnyError for `URLSession.reactive.data(with:)`

### PR DESCRIPTION
**Pull request by ikesyo**
https://github.com/antitypical/Result/pull/198

### CODE REVIEW

**Comment by sharplet** [comment]
Is there a way we can provide a deprecation warning for this change? I'm unsure what the impact of this change would be on code expecting `NSError`.

**Comment by ikesyo** [comment]
> Is there a way we can provide a deprecation warning for this change?

Something like this? 😉

**Comment by sharplet** [comment]
Looks good

**Comment by mdiep** [comment]
Why isn't `NSError` correct here? Isn't that what the Foundation API will have returned?

**Comment by sharplet** [comment]
It's bridged as `Error`, so I think it makes us a better Swift 3 citizen to preserve that as accurately as possible.

**Pull request merged**
