### PR TITLE
Added comment to DispatchSourceTimerWrapper.Equatable

### PR DESCRIPTION
**Pull request by NachoSoto**
#### Checklist
- [ ] Updated CHANGELOG.md.

### CODE REVIEW

**Comment by mdiep** [comment]
Good thing these will be synthesized soon!

**Comment by jjoelson** [comment]
I tried to implement equality this way initially but [had to change it](https://github.com/ReactiveCocoa/ReactiveSwift/pull/584/commits/7911a7366c4c585207186305c7be08d00eac6471) because it seems `DispatchSourceTimer` doesn’t inherit from `NSObjectProtocol` on Linux.

**Comment by NachoSoto** [comment]
OMG I'm blind, I just noticed the 3 `===`... I'm going to add a comment instead.

**Comment by NachoSoto** [comment]
Okay, added a comment...

**Pull request merged**
