### PR TITLE
Introducing Trigger

### PR DESCRIPTION
**Pull request by Marcocanc**
## Description

`Trigger` provides a simple wrapper for Signals that are used to *trigger* something through `Void`.
It conforms to `BindingSource` and `BindingTargetProvider`.

## Motivation

I find myself using `MutableProperty<()>` way too often, especially for my ViewModel inputs.

## Todo

- I'm not entirely sure which verb is the most adequate for the use-case. I've used `fire` for now.
- Proper documentation
- Maybe a Playground example?

### CODE REVIEW

**Comment by brow** [comment]
How are you using `MutableProperty<()>`? I am curious because I have none of those in my codebase, in view models or elsewhere.

**Comment by Marcocanc** [comment]
@brow for example when there's a button press. It's used extensively in the [Kickstarter App](https://github.com/kickstarter/ios-oss/) and I started using it since it takes less code than creating a Signal pipe.

**Comment by brow** [comment]
Ah, thanks for the example. In my own projects, I do something like:
```swift
//ViewModel.swift
protocol ViewModelInputs {
    var viewDidAppear: () -> ()
}
// ViewController.swift
self.reactive.viewDidAppear.observeValues(viewModel.viewDidAppear)
```
(I'm assuming your `reactive.viewDidAppear` is convenience method for `reactive.trigger(for: #selector(viewDidAppear))`.)

Is that equivalent? Do you see one as preferable?

**Comment by brow** [comment]
Possibly relevant: https://github.com/ReactiveCocoa/ReactiveSwift/issues/78

**Comment by Marcocanc** [comment]
Sure that works too, but I try to stay fully reactive when binding my ViewModels and ViewControllers, since most inputs will result in an output.

**Comment by andersio** [comment]
[This appears to be a specialised `(Publish)Subject` from which we have moved away since the swing to Swift](https://github.com/ReactiveCocoa/ReactiveSwift/issues/78). I understand the ergonomic aspect of this, and admittedly I had been utilising `Action` in a similar manner. But I personally would stand by the argument of not encouraging this from an API surface perspective, and hence not incorporating this as part of the framework.

If you find creating multiple pipes a bit of a boilerplate, grouping the events as an enum and having a signal of events could potentially be a way out.

**Pull request closed without merging**
