### PR TITLE
Build ReactiveSwift with Swift 4.0.

### PR DESCRIPTION
**Pull request by andersio**
Drop Xcode 8.3 support.

#### Checklist
- ~~Updated CHANGELOG.md.~~

### CODE REVIEW

**Comment by ikesyo** [comment]
Will this be shipped as a part of ReactiveSwift 2.1? I'm not confident that if it is okay to drop Xcode 8.3 / Swift 3.1 support in the minor release.

**Comment by andersio** [comment]
🤔 ping @ReactiveCocoa/reactiveswift

**Comment by andersio** [comment]
We can bump straight to 3.0 if this is a huge concern.

**Comment by mdiep** [comment]
I think this requires a major version bump.

**Pull request merged**
