### PR TITLE
Rename `Lifetime.makeLifetime` to `Lifetime.make`.

### PR DESCRIPTION
**Pull request by andersio**

### CODE REVIEW

**Comment by sharplet** [comment]
On the grounds of "omit needless words" this seems like a good change. I was initially concerned about just using "make" because of ambiguity using leading dot syntax. But now that I think about it, leading dot syntax isn't possible in this case because the method returns a tuple, so 👍 from me.

The documentation will need to be updated too. Might be worth just grepping the project for any use of `makeLifetime`.

**Comment by mdiep** [comment]
I don't love either option, but this seems like an approvement. 👍 

This will need to deprecate the old version before it can be merged.

**Comment by andersio** [comment]
@mdiep `Lifetime.makeLifetime` was not part of any release.

**Comment by sharplet** [comment]
@andersio Will you be able to update the docs and examples for this too?

**Comment by andersio** [comment]
I already grepped the project. It doesn't seem there is anything else.

**Comment by sharplet** [comment]
The README and Framework Overview both have references to `makeLifetime`.

**Comment by andersio** [comment]
Whoops.

**Comment by andersio** [comment]
Whoops.

**Pull request merged**
