### PR TITLE
Prefer generic parameters to `Scheduler` existentials.

### PR DESCRIPTION
**Pull request by andersio**

### CODE REVIEW

**Comment by sharplet** [comment]
What's the benefit of this change?

**Comment by andersio** [comment]
No apparent benefit for now. Ideally this would allow the compiler to "see through" the interface and perform specialisation. But it doesn't because we do not have cross-module optimisation (yet).

Auto-promotion of existentials to generic parameters is one of the ABI stability items, btw.

**Comment by sharplet** [comment]
Given that it makes the method signatures a little harder to read, I feel like I'm 👎 on this for now

**Comment by mdiep** [comment]
> Given that it makes the method signatures a little harder to read, I feel like I'm 👎 on this for now

I agree. Let's do this when/if there's some benefit.

**Pull request closed without merging**
