### PR TITLE
Fix shared state in retry

### PR DESCRIPTION
**Pull request by sebastiangrail**
This fixes an issue where state is shared between different `start` invocations of the same producer.

```swift
let p = someProducer.retry(upTo: 1, interval: interval, on:scheduler)

p.start(...) // This consumes retries for the purpose of delaying errors
...
p.start(...) // Retries for the purpose of delaying errors can be negative here, resulting in the last error not being sent immediately.
```

#### Checklist
- [x] Updated CHANGELOG.md.

### CODE REVIEW

**Comment by sebastiangrail** [comment]
@andersio Could you review this PR, please?

**Comment by NachoSoto** [comment]
Could you write a test for this?

**Comment by Deloww** [comment]
- [ ] []()

**Review by Deloww — COMMENTED** [review]
- [ ] [](https://github.com/ReactiveCocoa/ReactiveSwift/pull/829/files)

**Pull request merged**
