### PR TITLE
Make non-class types be able to conforms to ReactiveExtensionProvider

### PR DESCRIPTION
**Pull request by ra1028**
This is very tiny changes.

#### Checklist
- [x] Updated CHANGELOG.md.

### CODE REVIEW

**Comment by mdiep** [comment]
I know there's been some discussion of removing this requirement before. Can you share an example of a non-class type where you'd like to use it?

**Comment by mdiep** [comment]
I'm not sure this is something that we want to support.

Reactive extensions only really make sense with a reference type. If you were trying to change a `struct` or `enum`, you'd have problems. I'm not sure if enabling other wrappers like this is worth it given that it might be confusing to users.

@ReactiveCocoa/reactivecocoa?

**Comment by sharplet** [comment]
I have had this particular use case before when writing extensions for Kingfisher, which uses a `.kf` extension provider for its UIKit wrapper functionality. The value returned from `.kf` is a class, which explains why I didn't have this limitation.

I'm not currently opposed to loosening the restriction, although as you say it doesn't make a lot of sense for binding targets. @mdiep is that the confusion you're thinking of? That users might make a binding target to a struct and then be confused that it doesn't mutate shared state?

**Comment by mdiep** [comment]
> @mdiep is that the confusion you're thinking of? That users might make a binding target to a struct and then be confused that it doesn't mutate shared state?

Yup.

**Comment by andersio** [comment]
> That users might make a binding target to a struct and then be confused that it doesn't mutate shared state?

This is unlikely to happen since `BindingTarget` does not support `inout` reference. So if the value is value type, mutations attempted in the closure would be blocked by the compiler.

**Comment by ra1028** [comment]
> Either way, this is a semantic error that IMO we shouldn't account for.

Agreed.

@mdiep 
How about?

**Pull request merged**
