### PR TITLE
Convert to Swift 4.2.

### PR DESCRIPTION
**Pull request by renatorodrigues**
#### Checklist
- [ ] Updated CHANGELOG.md.

## Changes
- [x] Update Quick and Nimble
- [x] Update project language to 4.2

### CODE REVIEW

**Comment by mdiep** [comment]
Thanks for the PR!

I'm not sure we want to move to 4.2 right now. That'd be a breaking change and it has little benefit at the moment.

**Comment by andersio** [comment]
Unlike Swift 4.1 with conditional conformance, the 4.2 mode doesn't seem to offer any new language feature which the library can take advantage of.

**Comment by mdiep** [comment]
> It shouldn't be a breaking change though, unless we used anything exclusive to 4.2+ modes.

I don't think it'll build in Xcode 9 if you've set the Swift version to 4.2.

**Comment by mdiep** [comment]
I guess our CI disproves that. But it'd be an issue as soon as you tried to use a 4.2+ feature.

**Comment by mdiep** [comment]
Superseded by #712. Thanks!

**Pull request closed without merging**
