### PR TITLE
Merge 1.1.3 into master.

### PR DESCRIPTION
**Pull request by calebd**
Carthage fails to build from source in Homebrew because the ReactiveSwift 1.1.3 tag is not in master. This is an attempt to bring that tag into master so the build works as expected.

Here is a failing build log:

```
-> brew upgrade carthage
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (caskroom/cask).

==> Upgrading 1 outdated package, with result:
carthage 0.23.0
==> Upgrading carthage 
==> Using the sandbox
==> Cloning https://github.com/Carthage/Carthage.git
Updating /Users/calebdavenport/Library/Caches/Homebrew/carthage--git
==> Checking out tag 0.23.0
Synchronizing submodule url for 'Carthage/Checkouts/Nimble'
Synchronizing submodule url for 'Carthage/Checkouts/Quick'
Synchronizing submodule url for 'Carthage/Checkouts/Result'
Synchronizing submodule url for 'Carthage/Checkouts/xcconfigs'
Synchronizing submodule url for 'Externals/Nimble'
Synchronizing submodule url for 'Supporting Files/Configuration Support'
Synchronizing submodule url for 'Externals/Nimble'
Synchronizing submodule url for 'Carthage/Checkouts/Nimble'
Synchronizing submodule url for 'Carthage/Checkouts/Quick'
Synchronizing submodule url for 'Carthage/Checkouts/Result'
Synchronizing submodule url for 'Carthage/Checkouts/xcconfigs'
Synchronizing submodule url for 'Externals/Nimble'
Synchronizing submodule url for 'Carthage/Checkouts/Nimble'
Synchronizing submodule url for 'Carthage/Checkouts/Quick'
Synchronizing submodule url for 'Carthage/Checkouts/ReactiveSwift'
Synchronizing submodule url for 'Carthage/Checkouts/Result'
Synchronizing submodule url for 'Carthage/Checkouts/xcconfigs'
Synchronizing submodule url for 'Externals/Nimble'
Synchronizing submodule url for 'Carthage/Checkouts/Nimble'
Synchronizing submodule url for 'Carthage/Checkouts/Quick'
Synchronizing submodule url for 'Carthage/Checkouts/Result'
Synchronizing submodule url for 'Carthage/Checkouts/xcconfigs'
Synchronizing submodule url for 'Externals/Nimble'
Synchronizing submodule url for 'Carthage/Checkouts/Argo'
Synchronizing submodule url for 'Carthage/Checkouts/Curry'
Synchronizing submodule url for 'Carthage/Checkouts/ReactiveSwift'
Synchronizing submodule url for 'Carthage/Checkouts/Result'
Synchronizing submodule url for 'Carthage/Checkouts/Runes'
Synchronizing submodule url for 'Carthage/Checkouts/Nimble'
Synchronizing submodule url for 'Carthage/Checkouts/Quick'
Synchronizing submodule url for 'Carthage/Checkouts/Result'
Synchronizing submodule url for 'Carthage/Checkouts/xcconfigs'
Synchronizing submodule url for 'Externals/Nimble'
remote: Counting objects: 7, done.
remote: Total 7 (delta 6), reused 7 (delta 6), pack-reused 0
Unpacking objects: 100% (7/7), done.
From https://github.com/ReactiveCocoa/ReactiveSwift
 * [new branch]        promoteerror -> origin/promoteerror
error: Server does not allow request for unadvertised object 92d73573a1b097e70fa56084e41b1af7272ad1ab
Fetched in submodule path 'Carthage/Checkouts/ReactiveSwift', but it did not contain 92d73573a1b097e70fa56084e41b1af7272ad1ab. Direct fetching of that commit failed.
Error: Failed to download resource "carthage"
Failure while executing: git submodule -q update --init --recursive
```

This pull request says there are conflicts and I'm not really sure how those should be handled.

### CODE REVIEW

**Comment by mdiep** [comment]
I think we literally just need the commits in `master`. So an empty merge commit that points to current `master` and `1.1.3` would suffice?

**Comment by mdiep** [comment]
I think we literally just need the commits in `master`. So an empty merge commit that points to current `master` and `1.1.3` would suffice?

**Comment by calebd** [comment]
Not sure what you mean. This pr is the result of running `git merge 1.1.3` on while `master`.

**Comment by mdiep** [comment]
I think you want to do a `git merge -s ours 1.1.3` from `master`.

**Comment by mdiep** [comment]
>        ours
>           This resolves any number of heads, but the resulting tree of the merge is
>           always that of the current branch head, effectively ignoring all changes from
>           all other branches. It is meant to be used to supersede old development history
>           of side branches. Note that this is different from the -Xours option to the
>           recursive merge strategy.

**Pull request merged**
