### PR TITLE
Add `SignalProducer.init` overloads for `NoError`

### PR DESCRIPTION
**Pull request by ikesyo**
See https://github.com/Carthage/Carthage/pull/2077#discussion_r129483994 and https://github.com/Carthage/Carthage/pull/2077#discussion_r129484077.

#### Checklist
- ~~[ ] Updated CHANGELOG.md.~~

### CODE REVIEW

**Comment by mdiep** [comment]
I don't understand what this adds. Could you elaborate? It seems like this would just increase conflicts and require more manual disambiguation.

**Comment by ikesyo** [comment]
To disambiguate something like this:

```swift
let producer1 = SignalProducer(value: "")
	.flatMap(.concat) { str -> SignalProducer<Int, AnyError> in .empty }

let producer2 = SignalProducer(["", ""])
	.flatMap(.concat) { str -> SignalProducer<Int, AnyError> in .empty }
```

**Comment by mdiep** [comment]
This breaks source compatibility, but maintains binary compatibility, correct?

**Comment by andersio** [comment]
I am not convinced that it is source breaking.

**Pull request merged**
